### ISSUE TITLE
Postgres Schema not available

### ISSUE THREAD

**Issue by srichakradhar** [aksxmtvnty9/Splitpanunga#4]
@pascerprano could you add the postgres schema also to the repo please?
with the `users` and `payments` tables..

**Comment by aanushh** [comment]
I will add it, thanks for letting me know.

**Comment by aanushh** [comment]
Please bear with me because this is an old project and I'm not currently maintaining it (but may be in the future) and the schema that i have uploaded might have some wrong data types. Please feel free to make necessary changes to make it work, thanks
